### ISSUE TITLE
Not working after upgrading to 24.04 and transmission rpc 7.0.10

### ISSUE THREAD

**Issue by pablo33** [pablo33/Gideon#22]
module import: transmission_rpc

```
Traceback (most recent call last):
  File "/home/pablo/commands/Gideon.py", line 2713, in <module>
    TrackDeletedTorrents(tc)
  File "/home/pablo/commands/Gideon.py", line 1499, in TrackDeletedTorrents
    if len(tc.info(HashString)) == 0:
           ^^^^^^^
AttributeError: 'Client' object has no attribute 'info'
```

Transmission rpc
[https://transmission-rpc.readthedocs.io/en/v7.0.10/](https://transmission-rpc.readthedocs.io/en/v7.0.10/)
